spring:
  application:
    name: auth-service

  profiles:
    active: local # 기본 프로파일 설정 (local)

server:
  port: 8081

jwt:
  secret-key: "####"
  access-token-expire-time: 120
  refresh-token-expire-time: 7200

---

spring:
  main:
    web-application-type: reactive

  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:mem:authdb;
    driver-class-name: org.h2.Driver
    username: sa
    password: ####

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resource:
        jwt:
          issuer-uri: http://localhost:8081/auth

---
spring:
  config:
    activate:
      on-profile: development

  datasource:
    url: jdbc:mysql://localhost:3306/auth
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ####
    password: ####

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resource:
        jwt:
          issuer-uri: http://dev-auth-service/auth

---
spring:
  config:
    activate:
      on-profile: production

  datasource:
    url: jdbc:mysql://localhost:3306/auth
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ####
    password: ####

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  security:
    oauth2:
      resource:
        jwt:
          issuer-uri: https://auth-service.example.com/auth
